# -*- coding: utf-8 -*-
"""01 - Projeto Quiz - GCP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y_HQzPbM_sF1MITQUoHtI9WzQPOl0qv_
"""

# proposição de Código simples para Quiz
# Sem dicionário ou Looping 


print("-=" *31)
print("\t Seja Bem vindxs ao quiz - SIMULADOS GCP!")
print("-=" *31)
resp_user = input("Deseja iniciar? [S/N] ")

if resp_user != "S":
  quit()

score = 0

print(" \n\n-------> Simulado 01 <-------...")
print("\n 01 - Instance templates are used to create a group of identical VMs. The instance templates include: \n\n (A) Machine type, boot disk image or container image, zone, and labels \n (B) Cloud Storage bucket definitions \n (C) A load balancer description \n (D) App Engine configuration file")
resp_01 = input("Resposta: ")

if resp_01 == "A":
  print("Correto!\n")
  score = score + 1
else:
   print("Errado!\n")

print("02 - The command-line command to create a Cloud Storage bucket is: \n\n (A) gcloud mb \n (B) gsutil mb \n (C) gcloud mkbucket \n (D) gsutil mkbucket")
resp_01 = input("Resposta: ")
if resp_01 == "B":
  print("Correto!\n")
  score = score + 1
else:
   print("Errado!\n")
  
print("-=" *31)
print(f"Quiz acabou... Pontuação: {score}/2")
print("-=" *31)